Repository filips123/GimVicUrnik, pull requests merged in 2021-02, with the labels that each got.

#3 added hours
  website/src/components/timetable/TimetableWeek.vue
  website/src/store/modules/settings.ts
  website/src/utils/hours.ts
  website/src/views/Settings.vue
  website/yarn.lock
Labels: enhancement

#4 Add support for viewing documents
  API/config.yaml.sample
  API/gimvicurnik/__init__.py
  API/gimvicurnik/updaters/eclassroom.py
  API/gimvicurnik/updaters/menu.py
  API/gimvicurnik/utils/url.py
  API/poetry.lock
  API/pyproject.toml
  website/package.json
  website/src/components/documents/DocumentList.vue
  website/src/store/modules/storage.ts
  website/src/views/Documents.vue
  website/yarn.lock
Labels: enhancement

#5 Fix date parsing & Improve entity list handling
  API/gimvicurnik/updaters/menu.py
  API/poetry.lock
  API/pyproject.toml
  website/package.json
  website/src/components/settings/entitySelection/SelectClass.vue
  website/src/components/settings/entitySelection/SelectClassroom.vue
  website/src/components/settings/entitySelection/SelectTeacher.vue
  website/yarn.lock
Labels: bug, enhancement

#6 Add support for new lunch schedule format
  API/gimvicurnik/errors/__init__.py
  API/gimvicurnik/errors/eclassroom.py
  API/gimvicurnik/updaters/eclassroom.py
  API/gimvicurnik/updaters/menu.py
Labels: bug

#7 Fix lunch schedule parsing when document is updated
  API/gimvicurnik/updaters/eclassroom.py
Labels: bug

#8 Add support for dark theme & Improve data collection options
  website/src/App.vue
  website/src/components/settings/DataCollectionSelection.vue
  website/src/components/settings/ThemeSelection.vue
  website/src/plugins/vuetify.ts
  website/src/registerSentry.ts
  website/src/store/modules/settings.ts
  website/src/views/Settings.vue
Labels: enhancement
